name: CI

on: [pull_request]

jobs:
 install:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
      run: yarn

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: yarn build
   